Jamf enhancement dev
JupiterOne/graph-jamf pull request #160
Opened 2024-06-19 06:23 UTC by poornima-metron

# Description

Thank you for contributing to a JupiterOne integration!

Please include a summary of the change and which issue is fixed. Please also
include relevant motivation and context. List any dependencies that are required
for this change.

## Summary

## Type of change

Please leave any irrelevant options unchecked.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## Checklist

### General Development Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### Integration Development Checklist:

Please leave any irrelevant options unchecked.

- [ ] I have checked for additional permissions required to call any new API
      endpoints, and have documented any additional permissions in
      `jupiterone.md`, where necessary.
- [ ] My changes properly paginate the target service provider's API
- [ ] My changes properly handle rate limiting of the target service provider's
      API
- [ ] My new integration step is instrumented to execute in the correct order
      using `dependsOn`
- [ ] I have referred to the
      [JupiterOne data model](https://github.com/JupiterOne/data-model/tree/main/src/schemas)
      to ensure that any new entities/relationships, and relevant properties,
      match the recommended model for this class of data
- [ ] I have updated the `CHANGELOG.md` file to describe my changes
- [ ] When changes include modifications to existing graph data ingestion, I've
      reviewed all existing managed questions referencing the entities,
      relationships, and their property names, to ensure those questions still
      function with my changes.

2024-06-19 07:50 UTC, suraj-metron requested changes

2024-06-19 07:50 UTC, suraj-metron commented on CHANGELOG.md
> +- Updated the code device group entity : missing groups
Updated the code for Device Group Entity

2024-06-19 07:50 UTC, suraj-metron commented on src/steps/devices/index.ts
> +        computerIdSet.add(computerDevice.id);
Why are we doing this? Is there a chance that computerDevice will have duplicate values in computerDevices?

2024-06-19 07:53 UTC, Bharatkk-metron commented on src/steps/devices/index.ts
> +        computerIdSet.add(computerDevice.id);
For a larger data set, this might be the case. In the previous code, they were checking for duplications therefore putting a check to avoid duplicate key errors.

2024-06-19 09:21 UTC, suraj-metron commented on src/steps/devices/index.ts
> +        computerIdSet.add(computerDevice.id);
ok

2024-06-19 10:21 UTC, poornima-metron commented on CHANGELOG.md
> +- Updated the code device group entity : missing groups
updated

2024-06-19 16:43 UTC, suraj-metron approved these changes

2024-06-26 22:26 UTC, VDubber commented on src/jamf/client.ts
> +      this.getResourceUrl('/computergroups'),
Does this endpoint support pagination?

2024-06-27 21:17 UTC, VDubber commented
@poornima-metron - On future PRs, please reference the Jira ticket or SOW associated with this work. Thanks!

2024-06-27 21:52 UTC, VDubber commented on src/steps/devices/index.ts
> +
```suggestion
  await iterateComputerGroups(client, async (computerGroup) => {
    const hasComputerKey = jobState.hasKey(
      generateEntityKey(Entities.COMPUTER_GROUP._type, computerGroup.name),
    );
    if (!hasComputerKey) {
      await jobState.addEntity(createComputerGroupEntity(computerGroup.name));
    }
  });

```

I would recommend using `hasKey` over `findEntity` as often as possible. hasKey is more performant. Please note this recommendation: @suraj-metron

Also, the code has an additional set of `{}`. Intentional?
And on line 491, the `computerGroupEntity` is being set without being used again. Intentional?

2024-06-27 21:57 UTC, VDubber commented on src/steps/devices/index.ts
> +          const groupHasComputerRelatioinship = createDirectRelationship({
groupHasComputerRelationship

2024-06-27 21:58 UTC, VDubber commented on src/steps/devices/index.ts
> +          // Some large Jamf datasets are causing issues with duplicate relationships,
Are we confident that the keys are actually unique? Before we start skipping relationships, we need to ensure that we are dealing with real duplicates.

2024-06-27 22:09 UTC, VDubber commented on src/steps/devices/index.ts
> +        .computer_group_memberships) {
```suggestion
        ?.computer_group_memberships) {
```
Are groups_accounts always not undefined?

2024-06-27 22:13 UTC, VDubber commented on src/steps/devices/index.ts
> +  await createComputerUsesProfileRelationships(logger, jobState);
This looks like a great opportunity to break this into a separate `Build Computer -USES-> User Profile` step.

Ideally a step collects data from a single endpoint or builds a single relationship. This integration does not follow that pattern well.

You can declare dependencies on the steps to ensure `jobState.iterateEntities` has data to iterate.

2024-06-28 10:05 UTC, poornima-metron commented on src/steps/devices/index.ts
> +          const groupHasComputerRelatioinship = createDirectRelationship({
fixed the typo

2024-06-28 11:00 UTC, poornima-metron commented on src/steps/devices/index.ts
> +          // Some large Jamf datasets are causing issues with duplicate relationships,
we actually followed the previous code, it is implemented in the same way. I saw the following comments:
// Some large Jamf datasets are causing issues with duplicate relationships,
// so check that we won't have a duplicate before creating.
With smaller datasets, we are sure we are not skipping any relationship that has a unique key. However, with larger datasets, it seems someone experienced issues, hence this check is in place and we are following the same approach.

2024-06-28 11:32 UTC, poornima-metron commented on src/steps/devices/index.ts
> +
removing computerGroupEntity as it is not used

2024-06-28 11:44 UTC, poornima-metron commented on src/steps/devices/index.ts
> +  await createComputerUsesProfileRelationships(logger, jobState);
separated the relationship as a new step

2024-07-01 05:47 UTC, poornima-metron commented on src/jamf/client.ts
> +      this.getResourceUrl('/computergroups'),
"Not really. According to the documentation [here](https://developer.jamf.com/jamf-pro/reference/findcomputergroups), this endpoint does not support pagination. Additionally, we have not implemented pagination in fetching mobile devices."

2024-07-01 16:30 UTC, VDubber commented
I think this PR is ready to be merged once the Build/test check is passing.

2024-07-02 10:14 UTC, poornima-metron commented on src/jamf/client.ts
> +      this.getResourceUrl('/computergroups'),
according to documentation it seems like [](https://developer.jamf.com/jamf-pro/reference/findmobiledevices) this api doesnot support pagination .

2024-07-02 17:01 UTC, VDubber commented
These changes need to be moved [here](https://github.com/JupiterOne/integration-deployments/tree/main/graph-public/graph-jamf). Closing this PR now.

2024-07-02 17:01 UTC, closed without merging